CC = gcc

CFLAGS = -Wall -Wextra -Werror

TARGET = bsq

SRCS = main.c
OBJS = $(SRCS:.c=.o)

all: (TARGET)
$(TARGET): $(OBJS)
      $(CC) $(CFLAGS) -o $(TARGET) $(OBJS)
clean:
      rm -f $(OBJS)

fclean: clean rm -f $(TARGET)

re: fclean all

.PHONY all clean fclean re
